 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  chinese_food_zh_cap:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - https://storage.googleapis.com/sfr-vision-language-research/xllm/datasets/sbu/sbu.json
              # - /raid/cfl/share/dongxuli/data/xllm/sbu/annotation/sbu.json
          storage:
              - /raid/cfl/data/Chinese-food-net/Chinese_food_net_train.json
      images:
          storage: /raid/cfl/data/Chinese-food-net
          # storage: /raid/cfl/share/datasets/vision_language/sbu_resize
