 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: pretrain_xllm_video
  load_finetuned: False
  finetuned: ""
  pretrained: "/raid/cfl/cn_pretraining_multi_dialog/xllm/xllm/output/BLIP2/Pretrain_stage2_1400w/20230405133/checkpoint_4.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16" # "fp16" 
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # OPT
  # opt_model: "facebook/opt-2.7b"
  opt_model: "/raid/cfl/cn_pretraining_multi_dialog/cache/chatglm6b"

  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
